Freshly coded new client
ChillFish8/rewrk pull request #24
Opened 2021-11-12 22:00 UTC by programatik29

- Reordered dependencies and removed their patch version.
- Much more readable and less complex client code.
- Better implemented timeouts.
- Better error messages.
- Use `anyhow` on client code.
- Error logging.
- Uses `tokio-native-tls` instead of `tokio-rustls`.

2021-11-14 08:09 UTC, ChillFish8 commented
Ill have to review this tomorrow but any reason for dropping rustls for native tls?

2021-11-14 09:51 UTC, programatik29 commented
Mainly for convenience on my part. Using `native-tls` results in less code.

2021-11-19 15:36 UTC, ChillFish8 commented
Bump test

2021-11-20 17:32 UTC, ChillFish8 requested changes

2021-11-20 17:32 UTC, ChillFish8 commented on src/http/mod.rs
> +use tower::{util::ServiceExt, Service};
I think rustfmt needs to be ran on these changes. 

My general style with imports is ordered and separated by whitespace:

- `std`
- `3rd party deps` 
- `crate/super/self` imports

2021-11-20 17:46 UTC, ChillFish8 approved these changes

2021-11-20 17:55 UTC, merged